# Generated by Django 3.1.4 on 2021-04-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20210422_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
